version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit_gateway_image
    container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit_server_image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:14-alpine
    container_name: shareIt-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

